# Generated by Django 6.1 on 2026-09-03 01:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actualizada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['-actualizada_en'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro')], default='unidad', max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='carta.categoria')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en', to='inventario.insumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='carta.plato')),
            ],
            options={
                'verbose_name': 'Ingrediente de receta',
                'verbose_name_plural': 'Ingredientes de receta',
                'unique_together': {('plato', 'insumo')},
            },
        ),
    ]
