# Generated by Django 5.1.2 on 2026-09-25 15:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=150)),
                ('categoria_nombre', models.CharField(blank=True, default='Sin categoría', max_length=150)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, default='unidad', max_length=10)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.insumo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-creado_en'],
            },
        ),
    ]
