# Generated by Django 6.1 on 2026-09-03 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('abierta', models.BooleanField(default=False)),
                ('sesion_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('servido', 'Servido'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_solicitada', models.BooleanField(default=False)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('inventario_descontado', models.BooleanField(default=False)),
                ('sesion_id', models.UUIDField(editable=False, null=True)),
                ('forma_pago_preseleccionada', models.CharField(blank=True, default='', max_length=20)),
                ('tasa_cambio_preseleccionada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carta.plato')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_numero', models.PositiveIntegerField()),
                ('forma_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo_cup', 'Efectivo CUP'), ('mixto', 'Mixto (mitad transferencia, mitad efectivo CUP)'), ('usd', 'USD')], max_length=20)),
                ('total_cup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_efectivo_cup', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_transferencia_cup', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mesera_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('cajera_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('items_snapshot', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
