# Generated by Django 6.1 on 2026-08-27 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_numero', models.PositiveIntegerField()),
                ('forma_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo_cup', 'Efectivo CUP'), ('mixto', 'Mixto (mitad transferencia, mitad efectivo CUP)'), ('usd', 'USD')], max_length=20)),
                ('total_cup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_efectivo_cup', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_transferencia_cup', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('items_snapshot', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
