# Generated by Django 6.1 on 2026-08-28 18:02

import uuid
from django.db import migrations, models


def vincular_pedidos_a_su_mesa(apps, schema_editor):
    Mesa = apps.get_model('pedidos', 'Mesa')
    Pedido = apps.get_model('pedidos', 'Pedido')
    for mesa in Mesa.objects.all():
        Pedido.objects.filter(mesa_id=mesa.id, sesion_id__isnull=True).update(sesion_id=mesa.sesion_id)


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_inventario_descontado_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='sesion_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sesion_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(vincular_pedidos_a_su_mesa, migrations.RunPython.noop),
    ]
