# Generated by Django 6.1 on 2026-08-28 18:07

from django.db import migrations, models


def cerrar_mesas_existentes(apps, schema_editor):
    Mesa = apps.get_model('pedidos', 'Mesa')
    Mesa.objects.all().update(abierta=False)


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_mesa_abierta_mesa_sesion_id_pedido_sesion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='abierta',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(cerrar_mesas_existentes, migrations.RunPython.noop),
    ]
