# Generated by Django 6.1.1 on 2026-09-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='grupo_para_llevar',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='modalidad',
            field=models.CharField(choices=[('mesa', 'Mesa'), ('para_llevar', 'Para llevar')], default='mesa', max_length=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='mesa_numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('por_confirmar', 'Esperando a la mesera'), ('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('servido', 'Servido'), ('entregado', 'Entregado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.mesa'),
        ),
    ]
