# Generated by Django 6.1 on 2026-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_mesa_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cajera_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='factura',
            name='mesera_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
