# Generated by Django 6.1 on 2026-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_factura_cajera_nombre_factura_mesera_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pago_preseleccionada',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tasa_cambio_preseleccionada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
