# Generated by Django 6.1.1 on 2026-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('cocina', 'Cocina'), ('mesera', 'Mesera'), ('cajera', 'Cajera')], default='administrador', max_length=20),
        ),
    ]
