# Generated by Django 6.1 on 2026-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cantidad_mesas',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='turno',
            name='platos',
            field=models.ManyToManyField(blank=True, related_name='turnos', to='carta.plato'),
        ),
    ]
